name: Dependency Update

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js (if applicable)
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change according to your project's requirements

      - name: Install dependencies
        run: npm install # Change this if using a different package manager

      - name: Run dependency update
        run: npm update # Change this if using a different package manager

      - name: Create Pull Request for Dependency Updates
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Automated Dependency Update'
          body: 'This pull request updates the dependencies.'
          base: main # Change this to your default branch if different
          branch: auto-update-dependencies
