name: CI - Build & Test

on:
  push:
    branches:
      - '**'  # Run on all branches
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck
        continue-on-error: false

      - name: Run tests with coverage
        run: npm run test:coverage
        continue-on-error: false

      - name: Check test coverage threshold
        run: |
          echo "📊 Checking coverage thresholds..."
          # Coverage report is generated in coverage/ directory
          # vitest should fail if coverage is below threshold (configured in vitest.config.ts)

      - name: Upload coverage to Codecov
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build application
        run: npm run build
        continue-on-error: false

      - name: Check build size
        run: |
          echo "📦 Build size analysis:"
          du -sh dist
          echo ""
          echo "📄 Main files:"
          find dist/assets -type f -name "*.js" -o -name "*.css" | while read file; do
            size=$(du -h "$file" | cut -f1)
            echo "  - $(basename $file): $size"
          done
          
          echo ""
          echo "⚠️ Large files (>500KB):"
          find dist/assets -type f -size +500k | while read file; do
            size=$(du -h "$file" | cut -f1)
            echo "  ⚠️ $(basename $file): $size"
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: matrix.node-version == '20.x'
        with:
          name: build-dist
          path: dist/
          retention-days: 7

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true  # Don't fail build on lint errors

      - name: Run Prettier check
        run: npm run format:check
        continue-on-error: true

  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: |
          echo "🔍 Running security audit..."
          npm audit --audit-level=moderate || true

      - name: Check for high/critical vulnerabilities
        run: |
          echo "🔒 Checking for high/critical vulnerabilities..."
          AUDIT_RESULT=$(npm audit --json --audit-level=high 2>/dev/null || echo '{"metadata":{"vulnerabilities":{"high":0,"critical":0}}}')
          HIGH=$(echo $AUDIT_RESULT | jq -r '.metadata.vulnerabilities.high // 0')
          CRITICAL=$(echo $AUDIT_RESULT | jq -r '.metadata.vulnerabilities.critical // 0')
          TOTAL=$((HIGH + CRITICAL))
          
          echo "High vulnerabilities: $HIGH"
          echo "Critical vulnerabilities: $CRITICAL"
          
          if [ "$TOTAL" -gt 0 ]; then
            echo "⚠️ Found $TOTAL high/critical vulnerabilities"
            echo "Run 'npm audit fix' to fix them"
            exit 1
          else
            echo "✅ No high/critical vulnerabilities found"
          fi

      - name: Check for secrets in code
        run: |
          echo "🔍 Scanning for potential secrets..."
          node scripts/check-secrets.js $(git ls-files) || exit 1

  success:
    runs-on: ubuntu-latest
    needs: [build-and-test, lint, security]
    if: always()

    steps:
      - name: Check all jobs status
        run: |
          if [ "${{ needs.build-and-test.result }}" != "success" ]; then
            echo "❌ Build and test failed"
            exit 1
          fi

          if [ "${{ needs.lint.result }}" == "failure" ]; then
            echo "⚠️ Lint failed but not blocking"
          fi

          if [ "${{ needs.security.result }}" != "success" ]; then
            echo "❌ Security check failed"
            exit 1
          fi

          echo "✅ All checks passed!"

